name: 🚀 Start UI [web]

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16, 'lts/*']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install local dependencies
        run: yarn install

      - name: Build the build version
        run: |
          sed -i "s/__DEVELOPMENT__/$GITHUB_RUN_ID ($(date +"%Y-%m-%d"))/g" app-build.json
          sed -i "s/__VERSION__/PIPELINE $GITHUB_RUN_ID/g" app-build.json
          sed -i "s/__COMMIT__/$GITHUB_SHA/g" app-build.json
          sed -i "s/__DATE__/$(date +"%Y-%m-%d %T")/g" app-build.json

      - name: Check coding rules and types
        run: yarn lint

      - name: Run unit tests
        run: yarn test:ci

      - name: Building
        run: yarn build
